### ISSUE TITLE
Upgrading vue breaks test

### ISSUE THREAD

**Issue by oskarrough** [eddyerburgh/avoriaz-ava-example#10]
Hi, it seems upgrading vue from from 2.2.6 to 2.4.1 breaks the tests.

To reproduce clone this repo and run `yarn upgrade vue`. I'm seeing the same in another repo using ava+vue but not avoriaz. Any ideas? Thank you.

Here's is the full log from my machine:

```bash
 S/f/avoriaz-ava-example $ yarn upgrade vue                                                 5s 475ms
yarn upgrade v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/904y[4/4] Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ vue@2.4.1
Done in 12.39s.
 S/f/avoriaz-ava-example $ yarn test                                                       12s 716ms
yarn test v0.27.5
$ ./node_modules/.bin/nyc ./node_modules/.bin/ava test/*.spec.js
[Vue warn]: Vue is a constructor and should be called with the `new` keyword
/Users/xxx/avoriaz-ava-example/node_modules/vue/dist/vue.runtime.common.js:4290
  this._init(options);
       ^

TypeError: this._init is not a function
    at Array.Vue$3 (/Users/xxx/avoriaz-ava-example/node_modules/vue/dist/vue.runtime.common.js:4290:8)
    at hook (/Users/xxx/avoriaz-ava-example/node_modules/require-extension-hooks/hook.js:15:26)
    at /Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/xxx/avoriaz-ava-example/node_modules/ava/lib/process-adapter.js:100:4)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/test/Bar.spec.js:1:10875)
    at Module._compile (module.js:569:30)
    at Module.replacementCompile (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at extensions.(anonymous function) (/Users/xxx/avoriaz-ava-example/node_modules/require-precompiled/index.js:13:11)
    at /Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/xxx/avoriaz-ava-example/node_modules/ava/lib/process-adapter.js:100:4)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/node_modules/ava/lib/test-worker.js:61:1)
    at Module._compile (module.js:569:30)
    at Module.replacementCompile (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at runMain (/Users/oskar/.node-spawn-wrap-33589-7c88cd103f9a/node:63:10)
    at Function.<anonymous> (/Users/oskar/.node-spawn-wrap-33589-7c88cd103f9a/node:166:5)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/Users/oskar/.node-spawn-wrap-33589-7c88cd103f9a/node:173:8)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
[Vue warn]: Vue is a constructor and should be called with the `new` keyword
/Users/xxx/avoriaz-ava-example/node_modules/vue/dist/vue.runtime.common.js:4290
  this._init(options);
       ^

TypeError: this._init is not a function
    at Array.Vue$3 (/Users/xxx/avoriaz-ava-example/node_modules/vue/dist/vue.runtime.common.js:4290:8)
    at hook (/Users/xxx/avoriaz-ava-example/node_modules/require-extension-hooks/hook.js:15:26)
    at /Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/xxx/avoriaz-ava-example/node_modules/ava/lib/process-adapter.js:100:4)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/test/Foo.spec.js:1:11749)
    at Module._compile (module.js:569:30)
    at Module.replacementCompile (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at extensions.(anonymous function) (/Users/xxx/avoriaz-ava-example/node_modules/require-precompiled/index.js:13:11)
    at /Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/xxx/avoriaz-ava-example/node_modules/ava/lib/process-adapter.js:100:4)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/node_modules/ava/lib/test-worker.js:61:1)
    at Module._compile (module.js:569:30)
    at Module.replacementCompile (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at runMain (/Users/oskar/.node-spawn-wrap-33589-7c88cd103f9a/node:63:10)
    at Function.<anonymous> (/Users/oskar/.node-spawn-wrap-33589-7c88cd103f9a/node:166:5)
    at Object.<anonymous> (/Users/xxx/avoriaz-ava-example/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/Users/oskar/.node-spawn-wrap-33589-7c88cd103f9a/node:173:8)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

  2 exceptions

  ✖ test/Bar.spec.js exited with a non-zero exit code: 1

  ✖ test/Foo.spec.js exited with a non-zero exit code: 1
-------------|----------|----------|----------|----------|----------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------|----------|----------|----------|----------|----------------|
All files    |    18.52 |      100 |        0 |    19.61 |                |
 .setup.js   |      100 |      100 |      100 |      100 |                |
 Bar.spec.js |       15 |      100 |        0 |    16.67 |... 22,23,24,25 |
 Foo.spec.js |       10 |      100 |        0 |    10.34 |... 39,40,41,42 |
-------------|----------|----------|----------|----------|----------------|
error Command failed with exit code 1.
```

**Comment by eddyerburgh** [comment]
This is an issue with `require-extension-hooks` @jackmellis

**Comment by jackmellis** [comment]
@eddyerburgh I upgraded vue and then for some reason deleting and regenerating the `yarn.lock` was enough to get things running smoothly again (for me at least).

**Comment by eddyerburgh** [comment]
@jackmellis great thanks Jack 😄

**Comment by oskarrough** [comment]
That was it. Hah, three hours down the drain.. Thank you both!
