### ISSUE TITLE
Tests don't actually work

### ISSUE THREAD

**Issue by syropian** [eddyerburgh/avoriaz-ava-example#3]
Cloned the repo, cd'd in, ran `yarn`, then ran `npm test`. Here's the failed output:

```
[Vue warn]: Vue is a constructor and should be called with the `new` keyword
/Users/user/Sites/avoriaz-ava-example/node_modules/vue/dist/vue.runtime.common.js:3789
  this._init(options);
       ^

TypeError: this._init is not a function
    at Array.Vue$2 (/Users/user/Sites/avoriaz-ava-example/node_modules/vue/dist/vue.runtime.common.js:3789:8)
    at hook (/Users/user/Sites/avoriaz-ava-example/node_modules/require-extension-hooks/hook.js:15:26)
    at Object.require.extensions.(anonymous function) [as .vue] (/Users/user/Sites/avoriaz-ava-example/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/Sites/avoriaz-ava-example/test/Bar.spec.js:3:1)
    at Module._compile (module.js:571:32)
    at extensions.(anonymous function) (/Users/user/Sites/avoriaz-ava-example/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/Sites/avoriaz-ava-example/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/Sites/avoriaz-ava-example/node_modules/ava/lib/test-worker.js:49:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
[Vue warn]: Vue is a constructor and should be called with the `new` keyword
/Users/user/Sites/avoriaz-ava-example/node_modules/vue/dist/vue.runtime.common.js:3789
  this._init(options);
       ^

TypeError: this._init is not a function
    at Array.Vue$2 (/Users/user/Sites/avoriaz-ava-example/node_modules/vue/dist/vue.runtime.common.js:3789:8)
    at hook (/Users/user/Sites/avoriaz-ava-example/node_modules/require-extension-hooks/hook.js:15:26)
    at Object.require.extensions.(anonymous function) [as .vue] (/Users/user/Sites/avoriaz-ava-example/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/Sites/avoriaz-ava-example/test/Foo.spec.js:3:1)
    at Module._compile (module.js:571:32)
    at extensions.(anonymous function) (/Users/user/Sites/avoriaz-ava-example/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/Sites/avoriaz-ava-example/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/Sites/avoriaz-ava-example/node_modules/ava/lib/test-worker.js:49:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

  2 exceptions

  ✖ test/Bar.spec.js exited with a non-zero exit code: 1

  ✖ test/Foo.spec.js exited with a non-zero exit code: 1
```

**Comment by eddyerburgh** [comment]
Hi, sorry about this.

Tests are fixed.

**Comment by syropian** [comment]
Thanks! Confirmed they pass on my end 🌟
